# Generated by Django 5.1.1 on 2026-02-23 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gymowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('idproof', models.FileField(upload_to='uploads')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gymowners/')),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('GYM_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gymowner')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='uploads')),
                ('url', models.TextField()),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gymowners/')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('GYM_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gymowner')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('GYM_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gymowner')),
                ('USERPROFILE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('GYM_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gymowner')),
                ('USERPROFILE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Medicalreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporttitle', models.CharField(max_length=200)),
                ('reportfile', models.FileField(upload_to='uploads')),
                ('description', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('USERPROFILE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Dietplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietplan', models.TextField()),
                ('date', models.CharField(max_length=200)),
                ('MEDICALREPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicalreport')),
                ('USERPROFILE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Aisummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('date', models.CharField(max_length=200)),
                ('MEDICALREPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicalreport')),
                ('USERPROFILE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AdminMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('admin_share', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gym_share', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('GYM_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gymowner')),
                ('PAYMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.payment')),
                ('USERPROFILE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Workoutlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('GYM_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gymowner')),
            ],
        ),
        migrations.CreateModel(
            name='Dailyexerciseplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantext', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
                ('WORKOUTLEVEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workoutlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Workoutroutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200)),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
                ('WORKOUTLEVEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workoutlevel')),
            ],
        ),
    ]
