# Generated by Django 5.1.1 on 2026-02-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexerciseplan',
            name='plantext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workoutlevel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workoutroutine',
            name='description',
            field=models.TextField(),
        ),
    ]
